
name: Upload artifact to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - '!hello.py'

jobs:

  build:

    name: Upload merged commit artifacts
    # runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: CumulusDS/get-yaml-paths-action@v0.1.0
      id: web-commit
      with:
        file: ./scripts/file.yml
        rev: web.revision

    - name: build upgrade archive
      env:
        VERSION_PATH: ./scripts/version_lock.json
      run: bash -c "eval $(pwsh ./scripts/export_vars.ps1) && echo hi && env"
