
name: Upload artifact to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - '!hello.py'

jobs:

  build:

    name: Upload merged commit artifacts
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: run
      run: |
        which perl
        readlink perl || true
        perl -v
        /c/strawberry/perl/bin/perl.exe -v || true
        # /c/msys64/usr/bin/perl.exe -v
        # /c/msys64/usr/bin/perl5.32.0.exe -v
        cpanm ExtUtils::Manifest
        cpanm ExtUtils::MakeMaker
        cpanm Pod::Usage

        diff -r /c/msys64/usr/bin/core_perl /usr/share/perl5/core_perl || true
        echo "................................."
        diff -r /c/strawberry/perl/lib /usr/share/perl5/core_perl || true
      shell: bash
