
name: Upload artifact to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - '!hello.py'

jobs:

  build:

    name: Upload merged commit artifacts
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: CumulusDS/get-yaml-paths-action@v0.1.0
      id: web-commit
      with:
        file: ./scripts/file.yml
        rev: web.revision

    - name: run
      run: |
        echo "The selected color is >>>>>> ${{ steps.web-commit.outputs.rev }}"
        gcm curl
        Invoke-WebRequest https://github.com/PreVeil/vendor/raw/master/key_menu/windows/KeyMenu-x86_64-2.3.0-winX-NET4.0.zip -OutFile "KeyMenu-Win7.zip"
        # curl -fail https://github.com/PreVeil/vendor/raw/master/key_menu/windows/KeyMenu-x86_64-2.3.0-winX-NET4.0.zip -OutFile "KeyMenu-WinX.zip"
      # shell: bash
