
name: Upload artifact to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:

  build:

    name: Upload merged commit artifacts
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name:
      run: |
        echo "hi"
        ls -lah .
        git rev-parse --verify HEAD
