
name: Upload artifact to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    name: Upload merged commit artifacts

    env:
      ARTIFACT_DIR: ${{ github.event.pull_request.head.sha }}${{ github.sha }}


    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name:
      id: haha
      run: |
        echo "hi"
        ls -lah .
        git rev-parse --verify HEAD
        echo $ARTIFACT_DIR
        # [[ "${{ matrix.os }}" == "macos-latest" ]] && echo "::set-output name=PLATFORM_TARGET::osx" || true
        [[ "ubuntu-latest" == "ubuntu-latest" ]] && echo "::set-output name=PLATFORM_TARGET::ubuntu-latest"
      shell: bash

    - name: ahah
      run: |
        echo ${{ steps.haha.outputs.PLATFORM_TARGET }}
        echo "xxxxxxxxx"
        echo $ARTIFACT_DIR
