name: Block

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verify-version
        uses: actions-cool/verify-files-modify@v1.2.0
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          forbid-paths: '.github/workflows/'
          comment: |
            Please don't modify this.
          skip-verify-users: 'asdf'
