name: Release
on:
  pull_request:
    # branches:
    #   - 'release/**'

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    # - name: pull-request
    #   uses: repo-sync/pull-request@v2
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     destination_branch: master
    #     pr_title: "Release branch: ${{ github.head_ref }}"
    # - name: update-pull-request
    #   uses: kt3k/update-pr-description@v1.1.0
    #   with:
    #     pr_title: "Release branch: ${{ github.head_ref }}"
    #     # pr_body: ${{ steps.description.outputs.description }}
    #     destination_branch: master
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: update-pull-request
      run: |
        echo ${GITHUB_REF##*/} 

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Push to ECR
      run: echo ${{ steps.extract_branch.outputs.branch }}

